### ISSUE TITLE
Piccolo issue

### ISSUE THREAD

**Issue by Josephhines** [DiatomStudio/Piccolo#11]
My piccolo is fully assembled to the specs [with ardunio uno]. However, when I run the tether usb sketch the cnc slowly moves around [mostly jerking motions in the Z axis] but never moves on to the test circles when i press the test button.

When i try to upload another drawing via controllo there is no discernable change. any thoughts?

any update as to when a help forum will be established? [the link is dead on the site]

**Comment by gregsaul** [comment]
Hi Joseph,

This potentially sounds like a issue caused by electrical noise from the servo's. Could you try adding  nice big capacitor between 5V and GND on your Arduino?

Greg

**Comment by Josephhines** [comment]
Hey Greg,

I currently have a 330uF 25v capacitor in place. still struggling  with the same issues. Any other thoughts?



![2015-03-21 15 23 16](https://cloud.githubusercontent.com/assets/9592561/6766480/8558b10e-cfde-11e4-9054-5dd54dc49316.jpg)
